---
- name: Upgrade Apache Tomcat on target VM
  hosts: tomcat
  become: yes
  vars:
    tomcat_version: 9.0.85
    tomcat_user: tomcat
    install_dir: /opt/tomcat
    tomcat_url: "https://dlcdn.apache.org/tomcat/tomcat-9/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"

  tasks:

    - name: Ensure required packages are installed (Debian/Ubuntu)
      apt:
        name: ['default-jdk', 'curl', 'wget']
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure required packages are installed (RHEL/CentOS)
      yum:
        name: ['java-1.8.0-openjdk-devel', 'wget', 'curl']
        state: present
      when: ansible_os_family == "RedHat"

    - name: Create tomcat group
      group:
        name: "{{ tomcat_user }}"
        state: present

    - name: Create tomcat user
      user:
        name: "{{ tomcat_user }}"
        group: "{{ tomcat_user }}"
        shell: /bin/false
        create_home: no
        system: yes

    - name: Download Tomcat
      get_url:
        url: "{{ tomcat_url }}"
        dest: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
        mode: '0644'

    - name: Create installation directory
      file:
        path: "{{ install_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Extract Tomcat
      unarchive:
        src: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "{{ install_dir }}"
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Change ownership of Tomcat directory
      file:
        path: "{{ install_dir }}"
        state: directory
        recurse: yes
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_user }}"

    - name: Create Tomcat systemd service file
      copy:
        dest: /etc/systemd/system/tomcat.service
        content: |
          [Unit]
          Description=Apache Tomcat Web Application Container
          After=network.target

          [Service]
          Type=forking

          Environment=JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk
          Environment=CATALINA_PID={{ install_dir }}/temp/tomcat.pid
          Environment=CATALINA_HOME={{ install_dir }}
          Environment=CATALINA_BASE={{ install_dir }}
          Environment='CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC'
          Environment='JAVA_OPTS=-Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom'

          ExecStart={{ install_dir }}/bin/startup.sh
          ExecStop={{ install_dir }}/bin/shutdown.sh

          User={{ tomcat_user }}
          Group={{ tomcat_user }}
          UMask=0007
          RestartSec=10
          Restart=always

          [Install]
          WantedBy=multi-user.target
      notify: Restart Tomcat

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable Tomcat service
      systemd:
        name: tomcat
        enabled: yes

    - name: Start Tomcat service
      systemd:
        name: tomcat
        state: started

  handlers:
    - name: Restart Tomcat
      systemd:
        name: tomcat
        state: restarted
