---
- name: Upgrade Apache Tomcat on target VM
  hosts: tomcat
  become: true

  tasks:
    - name: Stop Tomcat (manual shutdown)
      ansible.builtin.shell: /opt/tomcat/bin/shutdown.sh || true
      args:
        executable: /bin/bash

    - name: Remove existing Tomcat directory
      ansible.builtin.file:
        path: /opt/tomcat
        state: absent

    - name: Extract new Tomcat archive
      ansible.builtin.unarchive:
        src: /tmp/apache-tomcat-9.0.85.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Rename extracted folder to /opt/tomcat
      ansible.builtin.command: mv /opt/apache-tomcat-9.0.85 /opt/tomcat

    - name: Make Tomcat scripts executable
      ansible.builtin.file:
        path: /opt/tomcat/bin/
        recurse: yes
        mode: '0755'

    - name: Start Tomcat (manual startup)
      ansible.builtin.shell: /opt/tomcat/bin/startup.sh
      args:
        executable: /bin/bash
