---
- name: Upgrade Apache Tomcat on target VM
  hosts: tomcat
  become: yes
  tasks:
    - name: Stop Tomcat service
      ansible.builtin.systemd:
        name: tomcat
        state: stopped
        enabled: true

    - name: Download latest Tomcat archive
      get_url:
        url: https://downloads.apache.org/tomcat/tomcat-9/v9.0.85/bin/apache-tomcat-9.0.85.tar.gz
        dest: /tmp/apache-tomcat-9.0.85.tar.gz

    - name: Extract Tomcat
      unarchive:
        src: /tmp/apache-tomcat-9.0.85.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Set symlink to latest Tomcat
      file:
        src: /opt/apache-tomcat-9.0.85
        dest: /opt/tomcat
        state: link
        force: true

    - name: Start Tomcat service
      ansible.builtin.systemd:
        name: tomcat
        state: started
        enabled: true
